# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rRiJoRBuA04IPU2kLp_FfD9D4INXDZFG
"""

# train_wrds.py
import numpy as np
import pandas as pd
import joblib

from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from feature_engineering import (
    portfolio_return_from_returns,
    build_features_from_returns,
    build_stock_features_for_kmeans
)

WRDS_CSV_PATH = "iiziq1bryuf0gssy.csv"

df = pd.read_csv(WRDS_CSV_PATH)

# Here is a general processing: Map possible column names to a unified name
col_map = {}
for c in df.columns:
    lc = c.lower()
    if lc in ["date", "dt"]:
        col_map[c] = "date"
    if lc in ["tic", "ticker"]:
        col_map[c] = "ticker"
    if lc in ["ret", "return"]:
        col_map[c] = "ret"

df = df.rename(columns=col_map)
required = {"date", "ticker", "ret"}
missing = required - set(df.columns)
if missing:
    raise ValueError(f"WRDS file missing columns: {missing}. Current columns: {df.columns.tolist()}")

df["date"] = pd.to_datetime(df["date"])
df["ticker"] = df["ticker"].astype(str).str.upper().str.strip()
df["ret"] = pd.to_numeric(df["ret"], errors="coerce")

# pivot -> rows=date, cols=ticker, values=ret
rets = df.pivot_table(index="date", columns="ticker", values="ret", aggfunc="mean").sort_index()
# 2) DEFINE TRAINING UNIVERSE
tickers_in_data = set(rets.columns)

if "SPY" not in tickers_in_data:
    raise ValueError("Training requires SPY in WRDS returns to build market_return. "
                     "If your WRDS data has no SPY, remove market_return feature in both train and app.")

# Select the portfolio asset pool
asset_pool = [t for t in rets.columns if t != "SPY"]

# To ensure stable training, first filter out stocks that are missing too much
min_obs = int(0.8 * len(rets))
asset_pool = [t for t in asset_pool if rets[t].notna().sum() >= min_obs]

use_cols = asset_pool + ["SPY"]
rets = rets[use_cols].dropna(how="all")

# 3) BUILD TRAINING SET (X, y)
# X: current_vol, portfolio_mean_return, market_return
# y_reg: future 20-day realized volatility
# y_cls: high-risk label

WINDOW = 20
N_PORTFOLIOS = 2000   
LOOKBACK_MIN = 120    

rets_assets_all = rets[asset_pool]
rets_spy = rets["SPY"]

dates = rets.index
valid_idx = np.arange(LOOKBACK_MIN, len(dates) - WINDOW - 1)

rng = np.random.default_rng(42)

X_list = []
y_reg_list = []

for _ in range(N_PORTFOLIOS):
    # random pick K assets and weights
    min_k = 3
    max_k = 7

    if len(asset_pool) < min_k:
      raise ValueError(
         f"asset_pool too small ({len(asset_pool)}). "
          "Relax missing-data filters or ensure more tickers are available in WRDS data."
     )

    K = int(rng.integers(min_k, max_k + 1))
    K = min(K, len(asset_pool))   # key fix
    chosen = rng.choice(asset_pool, size=K, replace=False)

    w = rng.random(K)
    w = w / w.sum()

    # random pick a time index
    i = int(rng.choice(valid_idx))
    t = dates[i]

    # slice past window returns to build features
    past_slice = dates[i - WINDOW + 1 : i + 1]
    future_slice = dates[i + 1 : i + 1 + WINDOW]

    rets_assets_past = rets.loc[past_slice, chosen].dropna()
    spy_past = rets_spy.loc[past_slice].dropna()

    # require enough observations
    if len(rets_assets_past) < WINDOW or len(spy_past) < WINDOW:
        continue

    X_row = build_features_from_returns(rets_assets_past, spy_past, w, window=WINDOW)

    # define future realized volatility label (regression target)
    rets_assets_future = rets.loc[future_slice, chosen].dropna()
    if len(rets_assets_future) < WINDOW:
        continue
    port_future = portfolio_return_from_returns(rets_assets_future, w)
    y_future_vol = float(port_future.std(ddof=1))

    X_list.append(X_row.iloc[0].to_dict())
    y_reg_list.append(y_future_vol)

X_train = pd.DataFrame(X_list)
y_reg = np.array(y_reg_list)

# classification label: high-risk if above median
threshold = np.median(y_reg)
y_cls = (y_reg > threshold).astype(int)

feature_cols = ["current_vol", "portfolio_mean_return", "market_return"]
X_train = X_train.reindex(columns=feature_cols)

# TRAIN MODELS
ridge = Ridge(alpha=1.0, random_state=42)
ridge.fit(X_train, y_reg)

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=6,
    random_state=42
)
rf.fit(X_train, y_cls)

# KMeans clustering model (per-stock features)
stock_features = build_stock_features_for_kmeans(rets_assets_all.dropna())
kmeans_scaler = StandardScaler()
Xk = kmeans_scaler.fit_transform(stock_features[["avg_return", "volatility", "avg_corr"]])

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
kmeans.fit(Xk)

# 5) SAVE ARTIFACTS
joblib.dump(feature_cols, "feature_cols.joblib")
joblib.dump(ridge, "ridge_model.joblib")
joblib.dump(rf, "rf_model.joblib")
joblib.dump(kmeans, "kmeans_model.joblib")
joblib.dump(kmeans_scaler, "kmeans_scaler.joblib")

print("Saved: feature_cols.joblib, ridge_model.joblib, rf_model.joblib, kmeans_model.joblib, kmeans_scaler.joblib")
print("Training samples used:", len(X_train))